"""Sample table created

Revision ID: 08e22f060541
Revises: 1d42be9828af
Create Date: 2025-04-09 21:56:29.005502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08e22f060541'
down_revision: Union[str, None] = '1d42be9828af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('samples',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('cod_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_uid', sa.Uuid(), nullable=False),
    sa.Column('user_uid', sa.Uuid(), nullable=False),
    sa.Column('sample_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('animal', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_reception', sa.DateTime(), nullable=False),
    sa.Column('date_taken', sa.DateTime(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('samples')
    # ### end Alembic commands ###
