"""relate samples to clients

Revision ID: c723e6691959
Revises: 08e22f060541
Create Date: 2025-04-11 10:24:47.185897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c723e6691959'
down_revision: Union[str, None] = '08e22f060541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('samples', 'user_uid',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'samples', 'users', ['user_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'samples', type_='foreignkey')
    op.alter_column('samples', 'user_uid',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
