"""deleting sample cod-ref

Revision ID: f9d709cf1e16
Revises: c723e6691959
Create Date: 2025-04-11 14:49:47.995649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f9d709cf1e16'
down_revision: Union[str, None] = 'c723e6691959'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('samples', 'cod_ref')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('cod_ref', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
